### PR TITLE
Default njodb.properties as a constructor argument

### PR DESCRIPTION
**Pull request by advplyr**
Add an optional constructor argument to override default properties when creating the njodb.properties file.

e.g.
`new njodb.Database(__dirname, { "datastores": 2, "lockoptions": { "update": 5000 } })`

### CODE REVIEW

**Comment by jamesbontempo** [comment]
Hey @advplyr :)

Thanks for the merge request!

I'm curious to learn a bit more about your proposed enhancement, especially since I've actually gone back-and-forth a bit on how best to provide a mechanism for people to modify an njodb database. A little backstory might be helpful...

I initially envisioned one might create an njodb database in a very "traditional" sort of way: by hand. That would mean creating an `njodb.properties` file in a specific directory (perhaps also with customized data and temp directories). I didn't expect that it would generally be the case that one would want to create a database dynamically in code.

That being said, I did figure that people might eventually want to modify a database configuration, and that's why I created the `setProperties` method. However, this method was sort of "naive" because it only changed the values in the configuration file. For example, it didn't actually resize a database if the number of datastores was changed, or move datastore files if a new data directory was specified. That's why I then created the `grow`, `shrink`, and `resize` methods which actually take care of redistributing data across the datastores. I hadn't created any other "management" methods (e.g., for changing the data directory and moving files) but that's only because I figured a method for resizing the database might be the highest priority. But then I realized that `setProperties` could be helpful in the constructor, so I added a call to it there; but as you see, only if an `njodb.properties` file doesn't already exist.

With that longwinded backstory out of the way, that now brings us to your merge request.

Lo and behold, you're proposing a way to create customized njodb databases dynamically in code! At one point I had actually played around with this a bit: I made the `setProperties` method private and called it from the constructor, either with the default configuration or using one that was passed in. This is basically what you've written, but I'm thinking that because the `setProperties` method only looks for specific configuration options, and also validates them, using it might be "safer" than your `deepAssignProperties` method.

So, I now have two questions for you:
1. Are you actually dynamically creating njodb databases in a project somewhere? This is as much a curiosity as it is a desire to understand the "use case" for a modified constructor.
2. Do you think using the `setProperties` method, called from the constructor, would achieve the desired effect?

Looking forward to your thoughts,
James

**Comment by advplyr** [comment]
Hey James,

I appreciate your explanation. I thought this must be something you decided against doing, or you just hadn't found the need for it yet. It sounds like you were somewhere in-between.

First off, I was intrigued by your project because I need a JSON db solution that is small and can be bundled in the same Docker container, eliminating the need for an external connection and a multi-container Docker setup.
The location of the data files are unknown before the Docker container is started. I could handle it in many different ways, like move the `njodb.properties` on launch, or just create it before initializing the `njodb.Database`, but it seemed to me the best solution is to initialize the database with the properties that I want.

On #2. If the `setProperties` method was called from the constructor with the optional argument, then the user would need to pass in a full properties object, rather then just specify which defaults they want to override. On second thought, `deepAssignProperties` method may not be necessary since I doubt anyone will need to just override individual `lockoptions` properties. In my case, I really just wanted to update the `datadir` and `datastores` from their default. The `setProperties` method would not accept `{ "datadir": "mydata", "datastores": 2 }`, for example.

Another option to consider is separating the actual creation of any files into a second step that would remain asynchronous. As it stands calling the constructor is synchronous.
```
var db = new njodb.Database(__dirname)
await db.initialize(myCustomProperties)
```
That would be a breaking change though.

**Comment by advplyr** [comment]
Okay, so I think I had a little misunderstanding. In my use-case I'm only talking about the initial creation.

It still holds that I think the best way for me to initialize the database with `datastores: 2` for example, would be from the constructor. However, as you tried to say, I can achieve the same thing like so:

```
var db = new njodb.Database(mypath)
db.resizeSync(2)
```

Anyway, still curious about your thoughts on a) setting your own properties on instantiation, and b) making the initialization asynchronous.

**Comment by jamesbontempo** [comment]
Thanks so much for sharing your use case! It's always exciting when someone finds something you created valuable and actually uses it :)

I wanted to let you know that I'm playing around with ways to achieve a deep merge of default and user-supplied properties. I dropped your `deepAssignProperites` code into mine but it isn't quite working. The linter is throwing an error about `target.hasOwnProperty`, and it also doesn't seem to be copying more than one level deep (for example, I tried setting the `stale` property of the `lockoptions` object but it wasn't "sticking"). All that to say that I agree that being able to supply user-defined properties to the constructor is a good idea, and not needing to pass the entire properties object is the way to go, so I'm working on it.

As for creating an asynchronous initialization, this is another thing I went back and forth on a bit. Where I landed was that I wanted the constructor to be synchronous (I read somewhere that asynchronous constructors were sort of an anti-pattern), and I also wanted it to return something substantive; that is, I wanted it only to return once the database was actually created. That being said, if you have a good use case for an asynchronous approach, I'm willing to hear it. But of course, you're right, introducing that would be a breaking change.

**Comment by jamesbontempo** [comment]
Alright, I just pushed a new version that allows for user-supplied properties to be passed to the constructor. Can you give it a try and see if it meets your needs? I hope so! And if so, I'll close this thread. Otherwise, if something doesn't seem quite right, just let me know...

**Comment by advplyr** [comment]
I pulled the update and it works great. Thanks for implementing that and for your work on this project.

**Comment by jamesbontempo** [comment]
Thanks for the idea! Glad to hear the updates worked out :) I'll go ahead and close the request. Let me know if there's ever anything else you need, or if you come up with any other good enhancement or new feature ideas...

**Pull request closed without merging**
